Algoritmo "calculo_fatorial"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Cálculo de um número ou mais "n" Fatorial (função)
// Autor(a)    : Yuri Mina Rampazo
// Data atual  : 02/02/2021
Var
c, n, nfat: inteiro


Inicio
escreval("Digite um número para saber o seu correspondente fatorial: ")
leia(n)
repita
      nfat <- n * (n-1)
ate(n-1 =1)


Fimalgoritmo