Algoritmo "conteate0"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Contagem regressiva de 10 a 0
// Autor(a)    : Yuri Mina Rampazo
// Data atual  : 01/02/2021
Var
contador: inteiro


Inicio
contador <- 10
enquanto (contador >= 0) faca
         escreval(contador)
         contador <- contador - 1
fimenquanto
escreval("Terminei de contar!")


Fimalgoritmo