Algoritmo "conteate10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Introdução a estruturas de repetição
// Autor(a)    : Yuri Mina Rampazo
// Data atual  : 01/02/2021
Var
contador: inteiro


Inicio
 contador <- 0
 enquanto (contador <= 10) faca
          escreval(contador)
          contador <- contador + 1
 fimenquanto
 escreval("Terminei de contar!")


Fimalgoritmo