Algoritmo "CREUZA_ 03"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Conversor graus (°F_°C)
// Autor(a)    : Yuri Mina Rampazo
// Data atual  : 20/01/2021
Var
 graus_c, graus_f: Real
Inicio
escreva("Qual é a temperatura nos Estados Unidos? ")
leia(graus_f)
graus_c <- ((graus_f -32)/1.8))
escreva("No Brasil a temperatura é de: ",graus_c," graus Celsius!")



Fimalgoritmo