Algoritmo "Creuza01"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Idade
// Autor(a)    : Yuri Mina Rampazo
// Data atual  : 20/01/2021
Var
ano_atual, ano_nasc, idade: Inteiro


Inicio
escreva("Em que ano nós estamos? ")
leia(ano_atual)
Escreva("Em que ano você nasceu? ")
leia(ano_nasc)
idade <- (ano_atual - ano_nasc)
escreva("Você faz: ",idade," anos em ",ano_atual)
Fimalgoritmo