Algoritmo "Creuza02"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Conversor de câmbio (Real_Dolar)
// Autor(a)    : Yuri Mina Rampazo
// Data atual  : 20/01/2021
Var
reais, dolares: Real


Inicio
escreva("Quantos reais você tem? R$ ")
leia(reais)
dolares <- (reais/5.30)
escreva("Se você tem R$",reais," , então você tem aproximadamente US$",int(dolares),"! ")

Fimalgoritmo
