Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Ler Variável
// Autor(a)    : Yuri Mina Rampazo
// Data atual  : 15/01/2021
Var
// Seção de Declarações das variáveis 
Nome: Caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva("Digite seu nome:")
 Leia (Nome)
 Escreval (" Muito prazer ", Nome,"!")
 Escreva (" Hoje você aprendeu a indexar uma variável! ")
Fimalgoritmo