Algoritmo "Hello, World!"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi ft. Gustavo Guanabara
// Descrição   : Apresentação ao mundo.
// Autor(a)    : Yuri Mina Rampazo
// Data atual  : 05/01/2021
Var
// Seção de Declarações das variáveis 
msg:caractere
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
msg <- "Olá, Mundo!"
Escreval("Eu aprendi o " , msg,"No VisualG!")
escreva("E me livrei da maldição!")
Fimalgoritmo