Algoritmo "PAR_OU_IMPAR"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Classificação de números pares e ímpares
// Autor(a)    : Yuri Mina Rampazo
// Data atual  : 20/01/2021
Var
   n: Real


Inicio
   escreva("Digite um número: ")
   leia(n)
   se (n%2=0) entao
      escreval("O número ",n," é par!")
   senao
      escreval("o número ",n," é impar!")
   fimse
Fimalgoritmo