Algoritmo "testeEscopo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/02/2021
Var
  n1, n2: inteiro
procedimento rotina (a, b: inteiro)
var
   x, y: inteiro
inicio
 x <- a
 y <- b
 escreva(n1, n2 , a, b, x, y)
fimprocedimento
Inicio
 n1 <- 5
 n2 <- 3
 rotina (n1, n2)
 escreva(n1, n2)
Fimalgoritmo